
export default function DisclaimersPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="space-y-4 mb-12">
        <h1 className="text-4xl font-bold tracking-tight">Disclaimers</h1>
        <p className="text-xl text-muted-foreground">
          Understanding the nature of content on Alternipedia.
        </p>
      </div>

      <div className="space-y-12">
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold border-b pb-2">
            1. Community Approximation
          </h2>
          <div className="prose dark:prose-invert max-w-none text-muted-foreground">
            <p>
              The content found on Alternipedia serves as a <strong>community approximation</strong> of what various political affiliations, groups, and ideologies believe.
            </p>
            <p className="mt-4">
              It is important for users to understand that:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>
                Articles and viewpoints are generated by the community and may not reflect objective facts or settled history.
              </li>
              <li>
                Representations of group beliefs are generalizations and may not apply to every individual within that group.
              </li>
              <li>
                The platform aims to capture the <em>perspective</em> of these groups as understood by our contributors, rather than an endorsement of those perspectives as absolute truth.
              </li>
            </ul>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold border-b pb-2">
            2. User-Generated Content
          </h2>
          <div className="prose dark:prose-invert max-w-none text-muted-foreground">
            <p>
              Alternipedia is a collaborative platform. Content is created, edited, and maintained by users. We do not guarantee the accuracy, completeness, or reliability of any information presented.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold border-b pb-2">
            3. No Professional Advice
          </h2>
          <div className="prose dark:prose-invert max-w-none text-muted-foreground">
            <p>
              Information provided on Alternipedia is for general informational and educational purposes only. It should not be construed as professional advice, whether legal, medical, financial, or otherwise. Always consult with a qualified professional for advice specific to your situation.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
